import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import App from "../components/layouts/app";
import Banner from "@/components/banders/banner";
import Tours from "@/components/tours/tours";
import News from "@/components/news/news";
import Sliders from "@/components/sliders/sliders";
import Blog from "@/components/blog/blog";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
          <App>
              <Banner/>
              <Tours/>
              <News/>

              <Blog/>
              <Sliders/>
          </App>
      </main>
    </>
  );
}
